### ISSUE TITLE
Inconsistent templated container implementation

### ISSUE THREAD

**Issue by Withaust** [godotengine/godot-cpp#1035]
One of the main reasoning for the way how Godot was architecturally made comes from a fact that it would never throw an exception and the game should try to run for as long as possible by printing errors and trying not to segfault until the very end. Current design of the templated containers acts in a complete opposite way to that. For example, in `HashMap` this is the implementation of the getter:
```
TValue &get(const TKey &p_key) {
	uint32_t pos = 0;
	bool exists = _lookup_pos(p_key, pos);
	CRASH_COND_MSG(!exists, "HashMap key not found.");
	return elements[pos]->data.value;
}
```
Why is `CRASH_COND_MSG` being used here? Why are we not returning a default `TValue` and printing the error instead?
Maybe, there needs to be a better, more cleaner way of handling situations like this instead of hard crashing the engine?

**Comment by Withaust** [comment]
This still seems to be the case. Its one thing to crash when out of memory like in [here](https://github.com/godotengine/godot-cpp/blob/master/include/godot_cpp/templates/local_vector.hpp#L70C4-L70C43), but it really should not be the case for the missing key.

**Comment by dsnopek** [comment]
One of godot-cpp's design goals is to work as similar as possible to the C++ code in the engine, with the goal that code can freely move between Godot and GDExtensions. In order to achieve that, we actually copy quite a few things wholesale from Godot, which includes the `HashMap` class in this case.

So, if we want to change this in godot-cpp, we'll need to change it in Godot first, otherwise we're introducing an inconsistency between Godot and godot-cpp.

**Comment by Withaust** [comment]
I see, so opening an issues about this in godot proposals is the way to address this then.
