### ISSUE TITLE
`NO_SAFE_CAST` doesn't fully forbid casting.

### ISSUE THREAD

**Issue by RechieKho** [godotengine/godot-cpp#1198]
### Godot version

Godot Engine v4.2.dev.custom_build.eb4301b94

### godot-cpp version

5834e16a221fde8dc0b6ca4b7a6721cc4b258037

### System information

Arch Linux, AMD ATI Radeon Vega Series / Radeon Vega Mobile Series, CPU: AMD Ryzen 3 3200G (4) @ 3.600GHz

### Issue description

I am making a GDExtension that runs tensorflow models. It uses [IREE](https://github.com/openxla/iree) to run the models. To compile it, runtime type id need to be turned off (-no-rtti), which means all of the casting is forbidden. In the past, I could just use `NO_SAFE_CAST` macro to turn off casting. But now in `include/godot_cpp/core/object.hpp`, there is a dynamic cast at line 153 and line 166.

I'm not sure whether `NO_SAFE_CAST` means turning off some of the cast or absolutely no cast. I do hope there is a macro to completely turn off casting. 

### Steps to reproduce

Compile godot-cpp with `NO_SAFE_FLAG` defined and `-fno-rtti` flag.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
`NO_SAFE_CAST` is no longer supported / defined anywhere in upstream Godot and godot-cpp, so it can't be disabled.

This used to be supported for Android and Web builds for size reasons, but since 4.0 both platforms use RTTI. See https://github.com/godotengine/godot/pull/65094, https://github.com/godotengine/godot/pull/66804, https://github.com/godotengine/godot-cpp/pull/1037#issuecomment-1427138825.

Whether that could be added back for godot-cpp only, I don't know. Since it interacts with the RTTI-enabled Godot but via a C interface, I guess godot-cpp could still work without RTTI.

Thoughts @dsnopek @Faless @mihe?

**Comment by mihe** [comment]
I'm curious as to why IREE requires RTTI to be disabled. As far as I'm aware RTTI shouldn't affect the ABI in any way. When skimming through the IREE repo it seems like it's maybe an issue with binary size?

Either way, I don't see why `NO_SAFE_CAST` (or some equivalent) couldn't be reintroduced and have `Object::cast_to` omitted entirely when it's defined.

Maybe also introduce a `Object::cast_to_unsafe` that does a `reinterpret_cast` instead, like `Object::cast_to` used to do, which would remain when `NO_SAFE_CAST` is defined. Although, I suppose that would end up being weirdly "semi-unsafe", since it would presumably only be unsafe when casting to a class exposed from the extension itself.

There are also ways to reimplement something like `dynamic_cast`, without having to resort to comparing strings, or even hashing them. I've worked in codebases that have done something similar to what [ctti](https://github.com/Manu343726/ctti) does, where you just do:

```cpp
template<typename T>
constexpr const void* get_my_custom_typeid() {
    return __PRETTY_FUNCTION__; // `__FUNCSIG__` on MSVC
}
```

... to give you a guaranteed unique type identifier that doesn't depend on RTTI being enabled, which can be stored with the rest of the class information and compared in some custom equivalent to `dynamic_cast`.

**Comment by mihe** [comment]
It just struck me that `Object::cast_to` is used in places within godot-cpp as well, which I guess puts a stop to the "omitting it entirely" strategy. Even if it was just about switching out the actual `dynamic_cast` within it, you'd probably be able to shoot yourself in the foot quite easily, without even realizing it, when dealing with stuff like `Variant`.

Anyway, the point about the custom type ID still stands I guess.

**Comment by dsnopek** [comment]
Well, `Object::cast_to<>()` is used extensively in module code to check if a class matches a particular type. Since one of the design goals for godot-cpp is to allow (as much as possible) the same code used in modules, I'm not sure it makes sense to have a "mode" where `Object::cast_to<>()` just does a reinterpret cast and doesn't check the type.

Coming up with a way for `Object::cast_to<>()` to check the type without using RTTI is a possibility. But I'm not sure if this is worth doing?

**Comment by RechieKho** [comment]
I have tried enabling rtti for iree by hacking the CMakeLists.txt. Everything work fine for noe. Hopefully there is no footgun in the future.
