### ISSUE TITLE
Accessing Dictionary from inside of Array results in a memory leak

### ISSUE THREAD

**Issue by Lasuch69** [godotengine/godot-cpp#1240]
### Godot version

4.1.1

### godot-cpp version

4.1

### System information

Fedora Silverblue 38

### Issue description

![image](https://github.com/godotengine/godot-cpp/assets/71460040/01d41ee8-526c-4716-b83f-3f7069cedf6d)
This function results in a memory leak.

Recreating this function line by line in GDScript doesn't result in memory leak.

I've tried to return Dictionary as is:
![image](https://github.com/godotengine/godot-cpp/assets/71460040/b6023238-7dab-4681-9471-5c733c62e09d)
Which works fine.

Callable and `callv()` are affected too.

### Steps to reproduce

N/A

### Minimal reproduction project

[gdextension-memory-leak-main.zip](https://github.com/godotengine/godot-cpp/files/12576484/gdextension-memory-leak-main.zip)

You can also view it here: https://github.com/Lasuch69/gdextension-memory-leak

**Comment by Lasuch69** [comment]
![image](https://github.com/godotengine/godot-cpp/assets/71460040/cf45c469-f06d-4ce7-82eb-a889f99514a8)
I'd like to add that in this function, leak is also present. It seems like accessing Dictionary from Array or TypedArray in any way leaks memory.

**Comment by dsnopek** [comment]
Thanks for the report!

Can you explain how you're detecting the memory leak?

**Comment by Lasuch69** [comment]
Memory graph rises indefinitely. I can check it with Valgrind like I did originaly.

**Comment by dsnopek** [comment]
I tried the MRP in the original description, and while Valgrind isn't reporting anything useful to me, I do see the memory rising constantly when this code is included:

```
		# Leaks
		var data: Dictionary = get_data()
```

... but the memory remains stable if I comment that out.

So, I'm seeing the leak too!

**Comment by allenwp** [comment]
System Info:
- Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 31.0.15.3598) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)
- GDExtension built with MSVC using godot-cpp 4.2.1 branch.

I have experienced a similar issue that might be the same root cause of this issue.

The following code leaks, but only in C++ GDExtension. If I compile this code as a part of the main Godot source, it does not leak.

```Array original_array;
for (int i = 0; i < 1000; i++) {
	Variant my_variant = original_array;
	Array my_array = my_variant; // This line causes memory to leak
}
```

The leak also happens if I used `Dictionary` or `TypedArray` instead of `Array`. I am able to see the leak in both the Godot editor as well as in Visual Studio when debugging my GDExtension:

![image](https://github.com/godotengine/godot-cpp/assets/17506573/635c29c4-88f0-4a02-9c3f-7cbd16c92e09)

I'll post any more details I have on this leak in this thread unless someone finds that this might actually be an independent issue.

**Comment by allenwp** [comment]
Alright, I understand what's happening now and I might have a fix(?) Here are the details:

I am going to use the `Dictionary` class for this example, as that is the class that was described in this original github issue, but this applies identically to the `Array` and `TypedArray` classes, and possibly others.

The leak happens when calling the `Dictionary` cast operator on GDExtension's `Variant`:

``` c++
Dictionary original_dictionary;
Variant my_variant = original_dictionary;
Dictionary my_dictionary = my_variant; // The cast operator of GDExtenion's Variant causes a leak
```
When this cast happens, a temporary `Dictionary` will be created and then a placement new will be performed on this temporary `Dictionary`. Here's what GDExtension's [current `Variant` cast operator ](https://github.com/godotengine/godot-cpp/blob/36847f6af0be548bae96429fa84d59f407b51582/src/variant/variant.cpp#L461-L465)looks like:
``` c++
Variant::operator Dictionary() const {
	Dictionary result;
	to_type_constructor[DICTIONARY](result._native_ptr(), _native_ptr());
	return result;
}
```

The `to_type_constructor[DICTIONARY](result._native_ptr(), _native_ptr());` line seems to perform a placement new using `result`, which has already been initialized with a `DictionaryPrivate`. When the placement new happens, it calls the [`Dictionary` copy constructor](https://github.com/godotengine/godot/blob/9adb7c7d130c6d4eb0e80b92d6eebd71fac3384d/core/variant/dictionary.cpp#L394-L397), which reasonably assumes that the `Dictionary` has not been initialized and overwrites the `DictionaryPrivate` pointer with the new one, causing the old one to leak:

``` c++
Dictionary::Dictionary(const Dictionary &p_from) {
	_p = nullptr;
	_ref(p_from);
}
```

**If** calling `to_type_constructor` with those two `_native_ptr()` will always perform a placement new, then a solution might be to do something like calling `Dictionary::~Dictionary()`, to make sure that the `Dictionary` has cleaned up its references and is ready to have its copy constructor called...

``` c++
Variant::operator Dictionary() const {
	Dictionary result;
	result.~Dictionary(); // Adding this line fixes the leak
	to_type_constructor[DICTIONARY](result._native_ptr(), _native_ptr());
	return result;
}
```
I have tested it and found that it successfully fixes the leak that was demonstrated in the original issue as well as the leak that I was experiencing.

But, this seems sub-optimal to be constructing a `Dictionary` just to destruct it immediately afterwards. And maybe even risky to be calling a destructor on an object with the expectation that it will always put everything in a state where it is valid to call the copy constructor again... So I'm currently looking into seeing if there is a safe way to do this by allocating some memory on the stack and then returning it once it has been filled in with the `Dictionary` data...

**Comment by dsnopek** [comment]
@allenwp Thanks for digging into this!

Can you try my draft PR https://github.com/godotengine/godot-cpp/pull/1378 and see if it fixes the leak for you?

I tested that it passed the automated tests, but I didn't have a chance to actually re-test the leak. If it works, I can try to use it in all the other applicable situations too.

**Comment by allenwp** [comment]
Thanks @dsnopek!

Unfortunately it looks like this method leaks (it leaves an `ArrayPrivate` in memory with a refcount of 1). I'm going to look into why this is, probably tomorrow.

**Comment by dsnopek** [comment]
> Unfortunately it looks like this method leaks (it leaves an ArrayPrivate in memory with a refcount of 1). I'm going to look into why this is, probably tomorrow.

The draft PR only did `Dictionary`, given that that was the topic of your last comment, so if you were testing `Array` that could certainly be why. :-) I'll update the PR to do `Array` too.

**Comment by allenwp** [comment]
Oh, sorry, my mistake on my comment — I adapted your PR code to `Array`, since that’s what I’ve been testing with, so that’s why I typed that. So I believe the issue I described does exist for all of these internally reference counted types.

Your proposed approach seems to work similar to some code I was fiddling with using uninitialized memory, but there seems to be an extra constructor call that I don’t quite understand yet.

**Comment by allenwp** [comment]
I've tried the original post's minimal reproduction project with the [4.2.2 godot-cpp release](https://github.com/godotengine/godot-cpp/releases/tag/godot-4.2.2-stable) and:

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 31.0.15.3598) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

And it is no longer leaking:

![image](https://github.com/godotengine/godot-cpp/assets/17506573/5f9e8ccf-53f7-415a-810c-3a4be1055b59)

I also tried with the old versions:

[4.1.1 godot-cpp release](https://github.com/godotengine/godot-cpp/releases/tag/godot-4.1.1-stable) and:

Godot v4.1.1.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 31.0.15.3598) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

![image](https://github.com/godotengine/godot-cpp/assets/17506573/8eff2aa6-8ced-46f4-837b-dccf5288dbfe)

This issue can now be closed! :)

**Comment by AThousandShips** [comment]
Thank you for updating!
