### ISSUE TITLE
missing 4.1.3 tag

### ISSUE THREAD

**Issue by Enhex** [godotengine/godot-cpp#1296]
### Godot version

4.1.3

### godot-cpp version

-

### System information

-

### Issue description

Godot 4.1.3 was released and there's no matching godot-cpp git tag

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by AThousandShips** [comment]
There also isn't a 4.0.4 tag, the 4.1.3 tag might be coming soon and just forgotten as 4.1.3 was released only yesterday

**Comment by akien-mga** [comment]
> There also isn't a 4.0.4 tag, the 4.1.3 tag might be coming soon and just forgotten as 4.1.3 was released only yesterday

I added the 4.0.4 tag.

For 4.1.3, @dsnopek did a lot of cherry-picks to the `4.1` branch since 4.1.2, so we might want to make sure that potential fixups have also been cherry-picked, and that it's ready to tag.

For now, I committed the `extension_api.json` change via df5b1a9a692b0d972f5ac3c853371594cdec420b, but didn't tag `godot-4.1.3-stable`.

**Comment by dsnopek** [comment]
The only PR pending cherry-picking that could be described as a fixup would be part of PR https://github.com/godotengine/godot-cpp/pull/1303, which fixes `disable_exceptions` on MSVC.

In any case, I just made a new cherry pick PR https://github.com/godotengine/godot-cpp/pull/1306

**Comment by akien-mga** [comment]
`godot-4.1.3-stable` is now tagged: https://github.com/godotengine/godot-cpp/releases/tag/godot-4.1.3-stable
