### ISSUE TITLE
`type-limits` check prevents compiling 4.2 version by GCC 11

### ISSUE THREAD

**Issue by grabusr** [godotengine/godot-cpp#1322]
### Godot version

4.2

### godot-cpp version

4.2-stable

### System information

Ubuntu 22.04.3 LTS, gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### Issue description

Compilation error is raised:
```
godot-cpp/src/godot.cpp:274:60: error: comparison of unsigned expression in ‘>= 0’ is always true [-Werror=type-limits]
  274 |                 compatible = internal::godot_version.patch >= GODOT_VERSION_PATCH;
```
Reason of that is we compare `uint32_t patch` variable with `GODOT_VERSION_PATCH`, which value is `0`.

### Steps to reproduce

Just try to compile tag `godot-4.2-stable` with gcc-11.4 in Release config

### Minimal reproduction project

Just try to compile tag `godot-4.2-stable` with gcc-11.4 in Release config

**Comment by akien-mga** [comment]
It's not an error, just a warning. But the OP's build has warnings treated as errors (`-Werror`).

I don't see where we'd enable this by default in the SCons setup, but it seems CMake forces it on, so that might be the problem.

`-Werror` shouldn't be enabled by default, because we can't control what warnings new compilers might find in the future.
