### ISSUE TITLE
GDExtension overide StaticBody3D's virtual _mouse_enter(),but it does'nt work ,if overide StaticBody3D's virtual _input_event,it will work

### ISSUE THREAD

**Issue by MAXFROMCODE** [godotengine/godot-cpp#1325]
### Godot version

4.2 stable

### godot-cpp version

4.2

### System information

win11

### Issue description

<img width="1468" alt="f6e7f8f06af74f5312d36ed4925b655" src="https://github.com/godotengine/godot-cpp/assets/142991584/09be1e51-91d2-4ef1-a2a7-01fb90f173d3">

i create a GDscript _mouse_enter() extend My new Class it work

### Steps to reproduce

create a  new Class public extend StaticBody3D,override <virtual void _mouse_exit()override> it doesn't work

### Minimal reproduction project

N/A

**Comment by MAXFROMCODE** [comment]
anyone what happend,please tell me ,I really want know why

**Comment by MAXFROMCODE** [comment]
<img width="1389" alt="1701504220208" src="https://github.com/godotengine/godot-cpp/assets/142991584/98ca82df-9f37-43a3-b56f-e69fdaf36b14">

**Comment by MAXFROMCODE** [comment]
_mouse_enter use UtilityFunctions::print("enter_mouse"); same bug

**Comment by dsnopek** [comment]
Thanks for the report!

This looks like a bug in Godot - there's this code in `CollisionOjbect3D':

```
void CollisionObject3D::_mouse_enter() {
	if (get_script_instance()) {
		get_script_instance()->call(SceneStringNames::get_singleton()->_mouse_enter);
	}
	emit_signal(SceneStringNames::get_singleton()->mouse_entered);
}

void CollisionObject3D::_mouse_exit() {
	if (get_script_instance()) {
		get_script_instance()->call(SceneStringNames::get_singleton()->_mouse_exit);
	}
	emit_signal(SceneStringNames::get_singleton()->mouse_exited);
}
```

It should be using `GDVIRTUAL_IS_OVERRIDDEN()` rather than checking if `get_script_instance()` is truthy. I'll make a PR to Godot.

**Comment by dsnopek** [comment]
I just posted PR https://github.com/godotengine/godot/pull/85870 which should fix this!

**Comment by dsnopek** [comment]
As an interim fix (before the PR is merged), you could connect to the `mouse_entered` and `mouse_exited` signals, rather than overriding the virtual methods

**Comment by AdSkipper1337** [comment]
Hello, I wanted to try the new GDExtension hot reloading and was playing arround with it when I got stuck with trying to have Area2D react to mouse events from GDExtension. I thought I was doing somehting wrong but turns out that was a genuine bug, and it is exactly the same error as here except for a slightly different case.
I already fixed it and made a PR https://github.com/godotengine/godot/pull/86908
Its essentially exactly the same fix, except for it also has the functions _mouse_shape_enter and _mouse_shape_exit which have the exact same behavior.

Maybe this issue should be generalized to cover both cases since they are so similar?

Best
