### ISSUE TITLE
Certain functions present in the wrapped class should be virtual

### ISSUE THREAD

**Issue by xana43** [godotengine/godot-cpp#1677]
### Godot version

v4.3.1.rc custom build b51be50

### godot-cpp version

4.3 stable 56571dc584ee7d14919996c6d58fb5b35e64af63

### System information

Fedora 41, RX 7900XT, AMD Ryzen 7950x

### Issue description

Certain functions that have no body to their implementation aren't marked as virtual in wrapped. I.E

`_notification, _set ,_get , _get_property_list, _property_can_revert, _property_get_revert, _validate_property`

while these functions are usable once they have been defined again in a derived class it doesn't really make much sense that these aren't virtual functions as they seem to fit the criteria for being as such.

### Steps to reproduce

- create a new class inheriting from object (or inheriting from a class that inherits from object)
- implement any of these functions
- most IDEs will say that these functions are hiding implementations of these functions

### Minimal reproduction project

N/A

**Comment by dsnopek** [comment]
Thanks!

One of the core design goals of godot-cpp is to try and match the API used internally by Godot, so that the same code can be used in Godot modules or in GDExtensions.

Those functions aren't `virtual` in Godot itself, they are `static` functions that are called via special virtual functions defined by the `GDCLASS()` macro - see: https://github.com/godotengine/godot/blob/master/core/object/object.h#L545

They are done the same way in godot-cpp, and isn't something we'll change unless it is changed in Godot first.

**Comment by xana43** [comment]
ah, so after reviewing wrapped.hpp again, I see how this works now. I think mainly it's that because these are called inside of the `GDCLASS()` macro and not formally overriden (at least most of the other functions besides `_notificationv()` it both confused my IDE and me.
