### ISSUE TITLE
Fatal error C1083: Cannot open include file: 'Godot.hpp': No such file or directory

### ISSUE THREAD

**Issue by GittyGrubHub85** [godotengine/godot-cpp#380]
I'm using GDNative documentation of Godot 3.2 and I'm stuck on this section (Compiling the Plugin): https://docs.godotengine.org/en/3.2/tutorials/plugins/gdnative/gdnative-cpp-example.html#compiling-the-plugin

Here's the build log:

> scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `bin\libgodot-cpp.windows.debug.default.lib' is up to date.
cl /Fosrc\gdexample.obj /c src\gdexample.cpp /TP /nologo -W3 -GR -EHsc -MDd -ZI /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_DEBUG /I. /Igodot-cpp\godot_headers /Igodot-cpp\include /Igodot-cpp\include\core /Igodot-cpp\include\gen /Isrc
gdexample.cpp
e:\godot\godot 3.2\projects (own)\gdnative c++ based on documents\gdnative_cpp_example\godot-cpp\src\gdexample.h(4): fatal error C1083: Cannot open include file: 'Godot.hpp': No such file or directory
scons: *** [src\gdexample.obj] Error 2
scons: building terminated because of errors. 

As I compiled with scons, it throws me the error of No such file or directory.
I've already generate its bindings including Godot.hpp

I'm using Visual Studio code with this and it can detect Godot.hpp and throws no errors but it throws errors on cmd scons command

I'm I missing something?

In this current section, my new SConstruct file was been combined with the old.

**Comment by Zylann** [comment]
In your SConstruct file, look at the lines with `env.Append(CPPPATH`.
These lines add directories for the compiler to look for header files. Among others, you should be able to find a path to the directory containing `Godot.hpp`.
Make sure it has the correct paths.

**Comment by Zylann** [comment]
Is this still an issue?
Typically this is due to your SConstruct file specifying the wrong path to the C++ bindings.

**Comment by ym210** [comment]
![image](https://user-images.githubusercontent.com/81609313/113510338-fe98b680-9577-11eb-9686-6299fde4814a.png)

what to do???

**Comment by ym210** [comment]
> ![image](https://user-images.githubusercontent.com/81609313/113510338-fe98b680-9577-11eb-9686-6299fde4814a.png)
> 
> what to do???

 fatal error C1083: Cannot open include file: 'gdnative_api_struct.gen.h': No such file or directory

**Comment by ym210** [comment]
> Is this still an issue?
> Typically this is due to your SConstruct file specifying the wrong path to the C++ bindings.

 fatal error C1083: Cannot open include file: 'gdnative_api_struct.gen.h': No such file or directory

![image](https://user-images.githubusercontent.com/81609313/113510448-7d8def00-9578-11eb-95bd-ed6503e4d073.png)

**Comment by Zylann** [comment]
Same thing, check your include paths. Recently `godot-headers` was renamed with a `-` instead of an `_` so make sure your paths are correct.

**Comment by kburchfiel** [comment]
I'm not seeing a file called Godot.hpp within my folders. There is one named godot.hpp, however. Could this difference in capitalization be part of the reason why I'm getting a similar error?

**Comment by Zylann** [comment]
The answer I gave were for GDNative in Godot 3. This might not apply to the master branch which is now GDExtension for Godot 4. But in general if your compiler cannot find a header it is also because of a similar problem: your include paths need a fix.

**Comment by Antoner8** [comment]
i dont have any godot.hpp or Godot.hpp file

**Comment by mistermeman** [comment]
Hi,

I don't seem to have a "Nativ"-directory. Is that bad? (LoL)

Also I attempted to` git copy` the `Godot-cpp` repository with Git Bash but it came without headers, so I `git copy` the headers repository  too, both via http. Is there a better way to do this? 

BTW I downloaded the Godot-cpp 4.2-Version and use the Godot 4.2.1-Version. 
Does that make sense or should I use master branch instead? However I had the exact same problem with master branch.

**Comment by dsnopek** [comment]
@mistermeman The headers repository isn't used with Godot 4, that's a Godot 3 thing. The headers are generated as part of the build process, running `scons` should automatically generate them.

**Comment by dsnopek** [comment]
@Archytas79 The headers should be generated by scons or cmake when you first attempt to build the project.

However, this issue was opened for GDNative on Godot 3, and really isn't relevant to any Godot 4 related problems. I'd recommend opening a new issue, with the command you're running and the errors your getting, along with information about your environment.

I'm going to close this issue.

**Comment by Seraphimt** [comment]
Hello! I have the same problem. I read the topic and did not find a solution, please help.

`scons: Building targets ...
Compiling platform\windows\console_wrapper_windows.cpp ...
Generating core\version_generated.gen.h ...
c1xx: fatal error C1083: �� 㤠���� ������ 䠩� ���筨�: platform\windows\console_wrapper_windows.cpp: No such file or directory,
Generating core\disabled_classes.gen.h ...
scons: *** [platform\windows\console_wrapper_windows.windows.editor.x86_64.obj] Error 2
scons: building terminated because of errors.`

**Comment by dsnopek** [comment]
There is no `platform\windows\console_wrapper_windows.cpp` file in godot-cpp - it looks like you're trying to compile Godot itself? If so, this should be a Godot issue (rather than godot-cpp), or perhaps addressed through support on one of the other Godot [community channels](https://godotengine.org/community/)
