### ISSUE TITLE
Ref<Reference> in generated headers

### ISSUE THREAD

**Issue by tastesliketriangle** [godotengine/godot-cpp#432]
So I'm trying to build the godot-cpp bindings. I've got the latest pull of the engine on the 3.2 branch, but when I run the scons file it fails because of object.hpp. specifically 2 lines that use `Ref<Reference>`.

**Comment by Zylann** [comment]
I'll add that on my local copy, `Object.hpp` does not contain any mention of `Ref` (while other classes do), which is right because otherwise it causes a cyclic reference. Even the engine's source code doesn't use `Ref<T>` in its declaration of `Object`.
So either the binding generator got recently changed and is wrong, or it used to be wrong and you got an old version somehow.

**Comment by Zylann** [comment]
From what I saw in my `api.json` (which I didnt touch since I generated my bindings a while ago), `Reference` used to be treated not as a reference, curiously:
```
    {
        "name": "Reference",
        "base_class": "Object",
        "api_type": "core",
        "singleton": false,
        "singleton_name": "",
        "instanciable": true,
        "is_reference": false,
```
Yet my bindings properly have `Ref<T>` in places like `Sprite::get_texture()`. I'm still not sure of how it went like that but we might have to add a special case to the `Object` class in the generator.

**Comment by Zylann** [comment]
This was caused by https://github.com/godotengine/godot/commit/8bc44c868ed61cfc0cf61e94391b02767253d469
So the bindings are currently "not broken" for versions prior to Godot `3.2.3`. The fix is still needed anyways, and shouldn't break with previous versions.
