### ISSUE TITLE
Object::cast_to causing unexpected behaviour

### ISSUE THREAD

**Issue by bengtsts** [godotengine/godot-cpp#528]
In `include/core/Ref.hpp`, the lines where 
```
    r.reference = Object::cast_to<T>(refb);
```
replaced 
```
    r.reference = (T *)refb;
```
have made the function `_input(const Ref<InputEvent> event)` run every frame --  even without an input event.
The result being `is_valid()` must be checked before calling `is_pressed()` or there is a crash.
E.g.;
```
void MyClass::_input(const Ref<InputEvent> event)
{
    // Now a required check!
    if (!joy_btn.is_valid()) return;

    if (joy_btn->is_pressed())
    {
        //...
    }
}
```

Looking at [#480](https://github.com/godotengine/godot-cpp/pull/480), its not clear to me whether this is the new intended behaviour or a bug.
Is `_input(const Ref<InputEvent> event)` **_not_** supposed to only be called when there is an input event?

**Comment by Calinou** [comment]
cc @Zylann

**Comment by Zylann** [comment]
> In include/core/Ref.hpp, the lines where
    r.reference = Object::cast_to<T>(refb);
replaced
    r.reference = (T *)refb;

What do you mean? Did you replace them yourself? The code of `Ref.hpp` does not cast this way. These lines are supposed to use `object_cast`, they mirror the same implementation used in Godot's source code https://github.com/godotengine/godot/blob/44e73473c6af24bc83ed2ec40a1c0162624dd8fc/core/object/reference.h#L139

> have made the function _input(const Ref<InputEvent> event) run every frame -- even without an input event.

I don't see how `_input(event)` can get called every frame without input event without Godot actually triggering it. This is not coming from the bindings, or there is some serious corruption going on somehow. Maybe it's a misunderstanding of how you expected `_input` to work. You are probably receiving another type of event which is not coming from a joypad button.

> void MyClass::_input(const Ref<InputEvent> event)
{
    // Now a required check!
    if (!joy_btn.is_valid()) return;

What is `joy_btn`? Assuming you have removed a bunch of code from this, the proper pattern to use in order to check input indeed requires to check `is_valid()`:

```cpp
void MyClass::_input(Ref<InputEvent> event) {
	Ref<InputEventJoypadButton> joy_btn = event;
	if(joy_btn.is_valid()) {
		if(joy_btn->is_pressed()) {
			//...
		}
	}
}
```

Because you only get the base class type as argument, and it can be any any of the subclasses, similarly to GDScript. So you have to downcast by doing this assignment (the cast is done by Ref<T>), and then check if it's indeed of that type. (you can also see that in Godot's source code as well https://github.com/godotengine/godot/blob/44e73473c6af24bc83ed2ec40a1c0162624dd8fc/editor/animation_bezier_editor.cpp#L617)

**Comment by bengtsts** [comment]
Sorry for my bad example. In my omitted code was a condition check that I hadn't taken into account. Which made my example doubly bad and even slightly confused me in my query.
I did further testing with the safer and older cast -- using simplified code -- to see the behavioural difference.

My confusion stemmed from not previously requiring an `is_valid()` check and my project always running flawlessly. But after the update to a safer cast, I got crashes with perfect consistency. Unless I added an `is_valid()` check.

Based on your example and the _animation_bezier_editor.cpp_ code you referenced. I take it using the `is_valid()` check was always the intended design, but wasn't properly implemented in GDNative until now?

**Comment by Zylann** [comment]
> I take it using the is_valid() check was always the intended design, but wasn't properly implemented in GDNative until now?

Yes, that's always been the way to go.

> not previously requiring an is_valid() check and my project always running flawlessly

What were you doing before exactly? Because if you cast without checking validity then it's either going to work by luck or crash randomly.

**Comment by bengtsts** [comment]
I'm not sure. This code runs without crashing on the unsafe cast. Moving the mouse and pressing a key registers in the print of **_event_**, but no crash.
```
void MyClass::_input(Variant event)
{
    Godot::print(event);
    const Ref<InputEventJoypadButton> joy_btn = event;
    if (joy_btn->is_pressed())
    {
        //...
    }
}
```

**Comment by Zylann** [comment]
`is_pressed()` is a function of `InputEvent` so this code works: https://docs.godotengine.org/en/stable/classes/class_inputevent.html#class-inputevent

However for anything more specific you may have to check.

**Comment by bengtsts** [comment]
Its likely because I needed fairly simple inputs that I didn't encounter any issue.
I'll be sure to make those checks going forward to take advantage of safer casting, and get in the habit of using them as a best practice; I have a lot of **static_cast**'s  to replace going forward.

Thanks for taking the time to help me out!!!
