### ISSUE TITLE
bash: scons: command not found problem (how to fix pls)

### ISSUE THREAD

**Issue by Onganne** [godotengine/godot-cpp#575]
I am extremely sorry for being a clueless person, I am just new to all of python, scons, and the other stuff related to that.
Honestly, I really didnt want to do this because I wanted to figure it out myself...and after three whole weeks...all my progress lead to nothing.

Now the problem...I do not understand why the git bash cannot find scons (or vice versa) as a command. I have been trying countless methods. Some more desperate than the others, including installing a new scons and copying it to that, but it was too confusing. It then lead to more problems like installing VENVs, trying to connect paths, and hopelessly trying to understand them all in the process...

and now i am here, asking for help, I really appreciate if there is a response that is beginner friendly, or even a response at all..

Maybe stuff explaining about what "PATH" actually is, whats the use of venv, and does any of it matter with this project, as the only real question I have is why scons is not being detected? Thx c:

here is what it said...at git
*******
User@User MINGW64 ~/SimpleLibrary
$ cd godot-cpp

User@User MINGW64 ~/SimpleLibrary/godot-cpp (master)
$ scons platform=windows generate_bindings=yes
bash: scons: command not found

User@User MINGW64 ~/SimpleLibrary/godot-cpp (master)
$ cd ..
*******

**Comment by aleksandrbazhin** [comment]
I installed it just a couple of days ago. Just install it globally with "python -m pip install scons", how it is described in SCons docs. Don't bother with VENV, it is a tool to have different packages for different projects in Python, seems like you don't need it. PATH is a system variable where windows (or some other os) would search for binaries. For example you can print "calc" and it would call calc.exe since it is located in one of the searchable folders (system32, or something like that). You can manually add some folder to PATH for it to become searchable, but you have to restart your terminal for changes to take effects.

**Comment by Onganne** [comment]
interesting, so to clarify, I just have to install another scons with "python -m pip install scons" on git bash.
and what o you mean by "install it globally"? If possible can you give me a link to the scons docs for I am a very sad and confused person, I again apologize haha
Also, thx for that description!

**Comment by aleksandrbazhin** [comment]
Here are the docs https://scons.org/doc/4.1.0/HTML/scons-user/ch01s02.html . When you install Python, it adds its /sripts/ folder to the PATH and when you install scons with pip, scons is installed there, so it becomes searchable by the system.
You can add your existing SCons path (where scons.exe is located) to your system PATH variable by hand. 
By "install it globally" i mean "forget about VENV" if you are new, you are just making your life more difficult.

You should probably close this issue, since it's mostly irrelevant to godot-cpp.

**Comment by aleksandrbazhin** [comment]
I was helped with my issue on the Godot Discord server, there is a chat room for gdnative. You probably should join with such questions.
