### ISSUE TITLE
I cannot modify the PacketVector3Array in the Array

### ISSUE THREAD

**Issue by 1419427247** [godotengine/godot-cpp#843]
![image](https://user-images.githubusercontent.com/33598732/190385802-04e510c7-f078-4e61-baa4-bd8307ae31e8.png)
It's my writing. What's wrong with it !(T_T)

**Comment by 1419427247** [comment]
![image](https://user-images.githubusercontent.com/33598732/190386062-4c71cf16-4fd6-4eb4-9717-0fcd8a42bd65.png)
The result is this  /(ㄒoㄒ)/~~

**Comment by Zylann** [comment]
```cpp
((PackedVector3Array*)(&kkk[0]))->push_back(Vector3i(1,2,3))
```
It starts being wrong from this line. `kkk[0]` gives you a `Variant&`. 
In C++, when you write `(PackedVector3Array*)(&something)`, you are forcing a raw casting of `something`, without caring about what that `something` is. You could do that on the value `42`, it would still compile. But this is not correct.
Yes, the language allows that. It's like: "Hey C++, I don't care about anything that could be wrong, just cast this no matter what". It's something you should only do when your really know what you are doing.
This will not work with `Variant&`. It might not crash, because the OS didn't detect memory overruns, but that doesnt mean the code works as intented either.

To obtain the `PackedVector3Array`, you may write this instead:
```cpp
PackedVector3Array array = kkk[0];
```
This works because `Variant` has an implicit conversion operator, so that in code like above it will automatically cast safely (If the variant isn't a `PackedVector3Array`, it will return an empty one).

Now if you want to modify the array:
```cpp
PackedVector3Array array = kkk[0];
array.push_back(Vector3i(1,2,3);
kkk[0] = array;
```
In Godot, `PackedVector3Array` has an unusual behavior: it performs Copy-On-Write. That means everytime you write something into it, if the array is referenced in multiple places, the place where you modified it will become a copy on its own, and changes will not reflect in other places that were referencing the array. This is why I assign the array back to `kkk[0]` so `kkk` will have the updated version.
