### ISSUE TITLE
Android `arm32` and `x86_32` architectures are not supported by NDK 25 via scons

### ISSUE THREAD

**Issue by DmitriySalnikov** [godotengine/godot-cpp#938]
Previously I used `Android.mk` to build with NDK 25 and it wasn't a problem. Now I found out that I can use `scons` to build for android directly to `.so`.
I simplified my CI script, but it turned out that 32-bit builds don't work with NDK 25.

Here are logs for arm32 with NDK 25: https://github.com/DmitriySalnikov/godot_qoi/actions/runs/3554264901/jobs/5970254673

And here are logs after changing version to NDK 23: https://github.com/DmitriySalnikov/godot_qoi/actions/runs/3554456032/jobs/5970566405

A copy of logs (in case CI logs are erased):
```
/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -o bin/libgodot_qoi.android.template_debug.arm32.so --target=armv7a-linux-androideabi18 -march=armv7-a -shared obj/qoi_import.os obj/qoi_save.os obj/qoi_wrapper.os obj/register_types.os -Lgodot-cpp/bin -lgodot-cpp.android.template_debug.arm32
ld: error: cannot open crtbegin_so.o: No such file or directory
ld: error: unable to find library -lc++
ld: error: cannot open crtend_so.o: No such file or directory
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/libgodot_qoi.android.template_debug.arm32.so] Error 1
scons: building terminated because of errors.
Error: Process completed with exit code 2.
```

**Comment by gilzoide** [comment]
Hi there! So, I ran into the same problem and found out what causes the issue and 2 ways to fix it.
So the problem is that godot-cpp Android tool [uses API level 18 for 32-bit architectures by default](https://github.com/godotengine/godot-cpp/blob/bf2f9e2f554bd22d127c744ca3d1a077b7bb5a63/tools/android.py#L11) and NDK 25 does not support API level 18, only 19 and newer.

If anyone comes here with the same problem, you don't necessarily have to downgrade NDK to 23 or another version that supports Android API level 18: the library builds fine using NDK 25 if you pass `android_api_level=19` (or a higher number, of course) to your `scons` invocation, like `scons platform=android arch=arm32 android_api_level=19`.
